name = "ai-news-api"
main = "index.ts"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "AI_NEWS", id = "67f7ddc5afb34290bfa096ed7542c3b1" }
]

[vars]
UPDATE_TOKEN = "CHANGE_ME_TO_RANDOM_SECRET"
